Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
sns.countplot(titanic['sex'], hue = titanic['survived'])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m<ipython-input-5-bc98e84ba233>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0msns[0m[0;34m.[0m[0mcountplot[0m[0;34m([0m[0mtitanic[0m[0;34m[[0m[0;34m'sex'[0m[0;34m][0m[0;34m,[0m [0mhue[0m [0;34m=[0m [0mtitanic[0m[0;34m[[0m[0;34m'survived'[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/anaconda3/lib/python3.8/site-packages/seaborn/categorical.py[0m in [0;36mcountplot[0;34m(data, x, y, hue, order, hue_order, orient, color, palette, saturation, width, dodge, ax, **kwargs)[0m
[1;32m   2940[0m         [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34m"Cannot pass values for both `x` and `y`"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2941[0m [0;34m[0m[0m
[0;32m-> 2942[0;31m     plotter = _CountPlotter(
[0m[1;32m   2943[0m         [0mx[0m[0;34m,[0m [0my[0m[0;34m,[0m [0mhue[0m[0;34m,[0m [0mdata[0m[0;34m,[0m [0morder[0m[0;34m,[0m [0mhue_order[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2944[0m         [0mestimator[0m[0;34m,[0m [0merrorbar[0m[0;34m,[0m [0mn_boot[0m[0;34m,[0m [0munits[0m[0;34m,[0m [0mseed[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.8/site-packages/seaborn/categorical.py[0m in [0;36m__init__[0;34m(self, x, y, hue, data, order, hue_order, estimator, errorbar, n_boot, units, seed, orient, color, palette, saturation, width, errcolor, errwidth, capsize, dodge)[0m
[1;32m   1528[0m                  errcolor, errwidth, capsize, dodge):
[1;32m   1529[0m         [0;34m"""Initialize the plotter."""[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1530[0;31m         self.establish_variables(x, y, hue, data, orient,
[0m[1;32m   1531[0m                                  order, hue_order, units)
[1;32m   1532[0m         [0mself[0m[0;34m.[0m[0mestablish_colors[0m[0;34m([0m[0mcolor[0m[0;34m,[0m [0mpalette[0m[0;34m,[0m [0msaturation[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.8/site-packages/seaborn/categorical.py[0m in [0;36mestablish_variables[0;34m(self, x, y, hue, data, orient, order, hue_order, units)[0m
[1;32m    435[0m             [0;32mif[0m [0mhue[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    436[0m                 [0merror[0m [0;34m=[0m [0;34m"Cannot use `hue` without `x` and `y`"[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 437[0;31m                 [0;32mraise[0m [0mValueError[0m[0;34m([0m[0merror[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    438[0m [0;34m[0m[0m
[1;32m    439[0m             [0;31m# No hue grouping with wide inputs[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mValueError[0m: Cannot use `hue` without `x` and `y`
ValueError: Cannot use `hue` without `x` and `y`

